project:
  type: website

website:
  title: "Cheatsheets"
  sidebar:
    contents: auto
    


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"



