project:
  type: website

website:
  title: "Cheatsheets"
  sidebar:
    contents: auto
    toos:
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    linestretch: 1.0



