project:
  type: website

website:
  title: "Cheatsheets"
  sidebar:
    contents: auto
    tools:
      - icon: github
        href: https://github.com/MoritzGuck/Code-Cheatsheets
    collapse-level: 3
  favicon: assets/favicon.png
  cookie-consent: true


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    linestretch: 1.0
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/moritzguck\.github\.io



