project:
  type: website

website:
  title: "Cheatsheets"
  sidebar:
    contents: auto
    tools:
      - icon: github
        href: https://github.com/MoritzGuck/Code-Cheatsheets

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    linestretch: 1.0



